[package]
name = "voxel_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
cgmath = "0.18.0"
env_logger = "0.10.0"
futures-intrusive = "0.5.0"
noise = "0.8.2"
pollster = "0.3.0"
wgpu = "0.17.0"
winit = "0.28.6"
